### ISSUE TITLE
Exempt users

### ISSUE THREAD

**Issue by YatsukiSama** [Lebyy/discord-voice#24]
It is possible to exempt a specific user from being tracked ? and track all the other ones

**Comment by Instinzts** [comment]
Yes, there is a way via a command. If you check the docs there is an option to exempt members. https://github.com/Lebyy/discord-voice I will leave the link here incase you looking forward checking it out! Have a great day and thanks for using Discord-Voice 😃

**Comment by YatsukiSama** [comment]
I tried but im getting an error

```
        const user = message.mentions.members.first() || message.guild.members.cache.get(args[0])

        exemptUser(user)
 
        async function exemptUser(user){
            try{
                await client.voiceTracker.updateConfig(message.guild.id, {
                    exemptMembers: (member) => member.id === user.id
                });
            } catch (err) {
                console.log(err)
                return client.utils.text(message, `:sweat_smile: | uh something weird occurred, please try again.`)
            }
            return client.utils.text(message, `:white_check_mark: | User: ${user} is now exempted from Voice Activity Tracking.`)
        }
```

Here is the error: 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at open (node:internal/fs/promises:410:10)
    at writeFile (node:internal/fs/promises:730:20)
    at VoiceManager.editConfig (C:\Users\yatsuki\Documents\GitHub\11pm-ranking\node_modules\discord-voice\src\Manager.js:320:15)
    at C:\Users\yatsuki\Documents\GitHub\11pm-ranking\node_modules\discord-voice\src\Config.js:389:32
    at new Promise (<anonymous>)
    at Config.edit (C:\Users\yatsuki\Documents\GitHub\11pm-ranking\node_modules\discord-voice\src\Config.js:369:16)
    at C:\Users\yatsuki\Documents\GitHub\11pm-ranking\node_modules\discord-voice\src\Manager.js:244:20
    at new Promise (<anonymous>)
    at VoiceManager.updateConfig (C:\yatsuki\anir\Documents\GitHub\11pm-ranking\node_modules\discord-voice\src\Manager.js:239:16)
    at exemptUser (C:\Users\yatsuki\Documents\GitHub\11pm-ranking\commands\voice\exempt.js:49:43) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by Instinzts** [comment]
Join Discord-Voice Support Server I will be able to help you there, best of luck Zen1th#7272. Link Here: https://discord.gg/2YBe2rrq
